### ISSUE TITLE
pytest in zsh-completions

### ISSUE THREAD

**Issue by blueyed** [alfredodeza/zsh-plugins#1]
Not a real issue, but wanted to let you know about https://github.com/zsh-users/zsh-completions/pull/454, because it's based on yours in the core.

**Comment by alfredodeza** [comment]
I recall getting some negative feedback about the implementation. I don't remember what was the exact technical detail on this, but you might want to get it reviewed by someone who has implemented completions with zsh before.

**Comment by blueyed** [comment]
Yeah, it's not my first completion adventure.
I guess the initial drawback is that it's rather slow, but I have added caching for that (which needs to be per sys.path / venv).

Closing this issue here.

**Comment by blueyed** [comment]
Please give it a try though, if you're using zsh + pytest still.
